<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LKNDSS25J6MQ2" ignored="0" name="EkalW TestCases" tests="5" failures="2" timestamp="03 Jan 2019 08:24:37 GMT" time="63.298" errors="0">
  <testcase name="test1" time="0.007" classname="com.ekalw.qa.testcases.MyRetryTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="com.ekalw.qa.testcases.MyRetryTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.ekalw.qa.testcases.MyRetryTest.test1(MyRetryTest.java:35)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.002" classname="com.ekalw.qa.testcases.MyRetryTest"/>
  <testcase name="takeScreenshotDemo" time="0.002" classname="com.ekalw.qa.base.ScreenshotTest">
    <skipped/>
  </testcase> <!-- takeScreenshotDemo -->
  <testcase name="takeScreenshotDemo" time="0.001" classname="com.ekalw.qa.base.ScreenshotTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.ekalw.qa.base.ScreenshotTest.takeScreenshotDemo(ScreenshotTest.java:30)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- takeScreenshotDemo -->
</testsuite> <!-- EkalW TestCases -->
